---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-config
  labels:
    name: bgg-config
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc

---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  labels:
    name: bgg-secret
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=
