---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: mysql-cluster
  labels:
    name: mysql-cluster
spec:
  replicas: 1
  secretName: mysql-secret

---
apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlDatabase
metadata:
  name: mysql-database
spec:
  database: wordpress
  clusterRef:
    name: mysql-cluster
