---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clientapp-pvc
  labels:
    name: clientapp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 1Gi

