---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    name: mysql-secret
type: Opaque
data:
  ROOT_PASSWORD: Y2hhbmdlaXQ=
  USER: cm9vdA==
  PASSWORD: Y2hhbmdlaXQ=
  DATABASE: d29yZHByZXNz
