---
apiVersion: wordpress.presslabs.org/v1alpha1
kind: Wordpress
metadata:
  name: wordpress-cluster
  labels:
    name: wordpress-cluster
spec:
  replicas: 2
  env:
    - name: DB_HOST
      value: mysql-cluster-mysql-master 
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: USER
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: PASSWORD
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: mysql-secret
          key: DATABASE
